---
kind: pipeline
type: docker
name: default

steps:
	- name: test ware
	  image: rust:alpine
		commands:
			- cargo install cargo-tarpaulin
			- cd ware
			- cargo test
			- cargo tarpaulin --coveralls ${COVERALLS}
		environment:
			COVERALLS:
				from_secret: coveralls_id
