---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: rust:alpine
    commands:
      - cargo test
  - name: coverage
    image: rust:alpine
    commands:
      - cargo install cargo-tarpaulin
      - cargo tarpaulin --coveralls ${COVERALLS}
    environment:
      COVERALLS:
        from_secret: coveralls_id
